# Generated by Django 4.2.1 on 2023-06-15 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuits',
            fields=[
                ('circuitid', models.CharField(db_column='circuitID', max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'circuits',
            },
        ),
        migrations.CreateModel(
            name='Constructors',
            fields=[
                ('constructorid', models.CharField(db_column='constructorID', max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'constructors',
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driverid', models.CharField(db_column='driverID', max_length=30, primary_key=True, serialize=False)),
                ('driver', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=20)),
                ('constructorid', models.ForeignKey(db_column='constructorID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.constructors')),
            ],
            options={
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='StatsDriverresult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('driverid', models.CharField(db_column='driverID', max_length=30)),
                ('driver', models.CharField(max_length=30)),
                ('position', models.IntegerField()),
                ('points', models.IntegerField()),
                ('constructor', models.CharField(max_length=50)),
                ('laps', models.IntegerField()),
                ('circuitid', models.CharField(db_column='circuitID', max_length=50)),
            ],
            options={
                'db_table': 'stats_driverresult',
            },
        ),
        migrations.CreateModel(
            name='DriverStandings',
            fields=[
                ('ds_id', models.AutoField(db_column='ds_ID', primary_key=True, serialize=False)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('constructorid', models.ForeignKey(db_column='constructorID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.constructors')),
                ('driverid', models.ForeignKey(db_column='driverID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.drivers')),
            ],
            options={
                'db_table': 'driver_standings',
            },
        ),
        migrations.CreateModel(
            name='DriversResults',
            fields=[
                ('dr_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('points', models.IntegerField()),
                ('laps', models.IntegerField()),
                ('circuitid', models.ForeignKey(db_column='circuitID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.circuits')),
                ('constructorid', models.ForeignKey(db_column='constructorID', max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.constructors')),
                ('driverid', models.ForeignKey(db_column='driverID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.drivers')),
            ],
            options={
                'db_table': 'drivers_results',
            },
        ),
        migrations.CreateModel(
            name='ConstructorStandings',
            fields=[
                ('cs_id', models.AutoField(db_column='cs_ID', primary_key=True, serialize=False)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('constructorid', models.ForeignKey(db_column='constructorID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.constructors')),
            ],
            options={
                'db_table': 'constructor_standings',
            },
        ),
    ]
