# Generated by Django 4.2.1 on 2023-06-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructorStandings',
            fields=[
                ('cs_id', models.AutoField(db_column='cs_ID', primary_key=True, serialize=False)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'constructor_standings',
                'managed': False,
            },
        ),
    ]
