# Generated by Django 4.2.1 on 2023-06-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_constructorstandings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConstructorStandings',
        ),
    ]
