# Generated by Django 4.2.1 on 2023-06-10 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_constructorstandings'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='constructorstandings',
            table='constructor_standings',
        ),
    ]
