# Generated by Django 4.2.1 on 2023-05-31 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0003_delete_constructors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Constructors',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='constructorID',
        ),
        migrations.RemoveField(
            model_name='driverresult',
            name='circuitID',
        ),
        migrations.RemoveField(
            model_name='driverresult',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driverstanding',
            name='constructor',
        ),
        migrations.RemoveField(
            model_name='driverstanding',
            name='driver',
        ),
        migrations.DeleteModel(
            name='Circuit',
        ),
        migrations.DeleteModel(
            name='Constructor',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='DriverResult',
        ),
        migrations.DeleteModel(
            name='DriverStanding',
        ),
    ]
